Add @layer support
wayfair/rainbow-sprinkles pull request #147
Opened 2023-06-08 16:26 UTC by aspirisen

## Description
Fixes: https://github.com/wayfair/rainbow-sprinkles/issues/146

Add `@layer` support

## Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wayfair/rainbow-sprinkles/blob/main/CONTRIBUTING.md)
- [x] Existing issues have been referenced (where applicable)
- [x] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [x] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [x] All new and existing tests pass

2023-07-06 21:25 UTC, roginfarrer commented on packages/rainbow-sprinkles/src/defineProperties.ts
> +}
Let's use this in `createStyles` and `createStaticStyles`. Move to the `types.ts` file if needed.

2023-07-06 21:28 UTC, roginfarrer requested changes
Looking good. Can we add tests for `createStyles` and `createStaticStyles`? To validate the object that we're passing to `style()`, not the actual CSS that's returned.

It would also be great to add a changeset and to update the package readme to add docs for using layers.

2023-07-09 15:08 UTC, aspirisen commented
Hey @roginfarrer 
I've made appropriate changes, could you please take a look again

2023-07-10 17:10 UTC, roginfarrer commented on .changeset/selfish-yaks-destroy.md
> +Add CSS @layer support
```suggestion
Support assigning properties to layers via `@layer` option on `defineProperties`

**Example usage:**

```ts
// sprinkles.css.ts
import { defineProperties } from 'rainbow-sprinkles';
import { layer } from '@vanilla-extract/css';

export const sprinklesLayer = layer();

const properties = defineProperties({
  '@layer': sprinklesLayer,
  // etc.
});
```
```

2023-07-10 17:11 UTC, roginfarrer commented on packages/rainbow-sprinkles/README.md
> +```
```suggestion
import { defineProperties } from 'rainbow-sprinkles';

export const responsiveLayer = layer('responsive');

const properties = defineProperties({
  '@layer': sprinklesLayer
  // etc.
});
```
```

2023-07-10 17:13 UTC, roginfarrer approved these changes

2023-07-10 17:15 UTC, merged